travis:
  secure:
    BINSTAR_TOKEN: mv9+JNSu6SFAzT+f++H9afCzccOJX3t6FWHGE+Wq/oZ928N6LF9RSYAPItTY54p9VcjeVL+wbT/APkqQopUp/VmcmdSRnPpkj7NWHi+kEXM590D1Di6vLsfL2VU8gmoo1zYI3MgxrclnammzNyQEvoajlTDJo5AbNX1kCLcdBFFV4pS763Sp4d8dKDwo6K/p5reiTp6Etavd6Imqj1Eyccyxpz2afarE/uLVH+jkzxGvE4qOVM6k4aQ0cL8r0N8efw+5BXWtQ56/ePjuHCGoBrtRsir9kO8NuQZDwcAd/7R/CoRLFaNjXlLnB/4ZimcVY+3HNMObzK+UfgTqMJaWe5dWek4JIy/EV5Od4/Ez0pchhNyOlN9HbTMr9a+xKVDjTc7fQVuCW4NUJOPiOVWuAdUrJV6y5lIaxvaQNXcu2SYvROeL0u7iKdXTUo/ZwKaffNe2cBiqgjMKJrbfP3FurS7WuvehJN+MoUkgHlvHEiY8kNqIbIXiT9QdcNN2U5c6KjWKC6w2heElI7W2Y5YrM2Uf0u21+RB+MLex1MDK4DvCgonURTPsuJ9hMEVbLEDml5NHXjab0sImdH77wYtp7uH2mLadPgnYCGbNxGCEq8vUfqp/UwXaYPtN5fNzspW+er2m15hqkS9m+8vWZFlh7RrNaXIAFBLSKaRQv6//5fE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
