travis:
  secure:
    BINSTAR_TOKEN: MOeNSHfhWSWvsezdkRzUQ8oxtzxoF9k8SJZMBzGQQ86eSdyeLJMFaCnLz/8+EkY6Sldgz+922n43HtMrL3nB6W4rLb8FjKqAkltM1gERJstQd5pzjDB72cBBbd42D1lnoIn1fLTmveMqdZApYbDmhv0sjRumNmfG50rPWLURiya/MIdLfrH5/BH8MQzIRppmgk3iSDILBLj0c2RXybb3FUmuyMPJvvYOabvLrdsOMoLDvZuub7L+NYOf+6jkJ8xf6OGKD9rWmVs1oel3qdhpzvxGz36pl68Z9U1sDj5GQ82X1qt/+yVPbJx/0BeItiTmmbozj+elTSU4bdDtGvAzcrtHPlhNYuaM+63LNuQbHEmedmPxBySCtyRL+6UQxoLnW6vIR7rZXr5+2luDWGHuUNrJ2oT2OHb7kcIPupTUPD+nUQ+gKrAXn8b2fAnEy+MCXWk6HzOc9AnF8ao9P1YnyGRWCdXXzwdoXxIx9plkvhrfBwDFzqCwWaqR+Svgm1yJtmt+NIPbHH/GV632jmKKBEMjE4ntg7VN4s+DNK8/ZVLr8inkPDKPV/ZRVRAj/m3yIb4zFGErMAPJngmfuz39fHrMEfvwPeTbjGw5pa9dEH9UKt6ZqpH8iBpTI4hI4HghzrPL1T/stmis7tgaXvtecsWNOKjkSx5pj5S6CQ6pm9g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
