travis:
  secure:
    BINSTAR_TOKEN: UaGCDGqeir+x3eH/dvuWwHaDgxfaOBOhAjd1dr49g0nnRxqw7c2d3KmHH6akG9OTo4XIkHStQljs8VnHgA2RXSJ4BmtJrNW/fOFSdWWAQ6s8eyK+a07T7nBhS4Y0btHGj+zrMbYQCjpGx4+GpCvVPuZLyOcupZrlVbPOXRjAceLmZhasx5NSgSUAokkQvD/FicGCg+i4kJem6OFsgnyJwYfODwEQo/XEPLi6EZjSWmnoNW6dkxCt45qYHxbIFRMHkKs3v8bTzpcJqzs+Wo/obEK1U1k3ftTcj8bI5Fj3rEi2K5Xj7xPblK9UfosIfMdHBuzdGqF97cczrSSiDsyaZf9IOn/cCOwZcrTIlpCF9JWrEgJ9soEfCQriX9s4Rpnt5RsZJgS1usStzhFuepM059CaHHCedZDV8GI8Bkz71p8eBKNueNbL5kJ9EEljSrTNpzvg34yC1YjYTVPphPtIJ+3y4MmV/i/YArlGm1EJ5sQXlbiUESqLETcLKriZQ4CDiZHCEUkZF9OEkwtOeICz+x7AuRHtqwBRdTX8T4qut2glKs8qN4eeczbiLE8aSunmTUAitL9ogVi+cyccnBLynREZXqZFwzXIBeOXjc9tbilxUHKH5hmgM3JI6qC5WiiV9OXTXh/vRny6+t6wD8wJ8gI95yuhA77qtIj6I8WKehI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
